# Generated by Django 3.2.9 on 2021-12-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='porte',
        ),
        migrations.AddField(
            model_name='animal',
            name='domestico',
            field=models.CharField(default='n/a', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='nome_animal',
            field=models.CharField(default='n/a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='predador',
            field=models.CharField(default='n/a', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='venenoso',
            field=models.CharField(default='n/a', max_length=5),
            preserve_default=False,
        ),
    ]
