# Generated by Django 4.1.1 on 2022-09-05 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0005_alter_receita_pessoa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receita",
            old_name="mode_preparo",
            new_name="modo_preparo",
        ),
        migrations.RenameField(
            model_name="receita",
            old_name="publicada",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="receita",
            old_name="pessoa",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="receita",
            name="data_receita",
        ),
        migrations.AddField(
            model_name="receita",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receita",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
