# Generated by Django 4.1.1 on 2022-09-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0006_rename_mode_preparo_receita_modo_preparo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receita",
            options={"verbose_name": "Receitas", "verbose_name_plural": "Receitas"},
        ),
        migrations.AlterModelTable(
            name="receita",
            table="receitas",
        ),
    ]
